python train.py file_name=../1_year_data/GData_train_0.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_0.m pca=True pca_name=pca_0.m model_name=model_0.m
python test.py file_name=../1_year_data/GData_test_0.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_0.m pca_name=pca_0.m model_name=model_0.m record_name=result_0.csv
python analyse_result.py predict_label_file_name=svm_result_0.csv true_label_file_name=GData_test_origin_0.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_0.txt
python train.py file_name=../1_year_data/GData_train_1.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_1.m pca=True pca_name=pca_1.m model_name=model_1.m
python test.py file_name=../1_year_data/GData_test_1.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_1.m pca_name=pca_1.m model_name=model_1.m record_name=result_1.csv
python analyse_result.py predict_label_file_name=svm_result_1.csv true_label_file_name=GData_test_origin_1.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_1.txt
python train.py file_name=../1_year_data/GData_train_2.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_2.m pca=True pca_name=pca_2.m model_name=model_2.m
python test.py file_name=../1_year_data/GData_test_2.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_2.m pca_name=pca_2.m model_name=model_2.m record_name=result_2.csv
python analyse_result.py predict_label_file_name=svm_result_2.csv true_label_file_name=GData_test_origin_2.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_2.txt
python train.py file_name=../1_year_data/GData_train_3.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_3.m pca=True pca_name=pca_3.m model_name=model_3.m
python test.py file_name=../1_year_data/GData_test_3.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_3.m pca_name=pca_3.m model_name=model_3.m record_name=result_3.csv
python analyse_result.py predict_label_file_name=svm_result_3.csv true_label_file_name=GData_test_origin_3.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_3.txt
python train.py file_name=../1_year_data/GData_train_4.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_4.m pca=True pca_name=pca_4.m model_name=model_4.m
python test.py file_name=../1_year_data/GData_test_4.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_4.m pca_name=pca_4.m model_name=model_4.m record_name=result_4.csv
python analyse_result.py predict_label_file_name=svm_result_4.csv true_label_file_name=GData_test_origin_4.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_4.txt
python train.py file_name=../1_year_data/GData_train_5.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_5.m pca=True pca_name=pca_5.m model_name=model_5.m
python test.py file_name=../1_year_data/GData_test_5.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_5.m pca_name=pca_5.m model_name=model_5.m record_name=result_5.csv
python analyse_result.py predict_label_file_name=svm_result_5.csv true_label_file_name=GData_test_origin_5.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_5.txt
python train.py file_name=../1_year_data/GData_train_6.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_6.m pca=True pca_name=pca_6.m model_name=model_6.m
python test.py file_name=../1_year_data/GData_test_6.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_6.m pca_name=pca_6.m model_name=model_6.m record_name=result_6.csv
python analyse_result.py predict_label_file_name=svm_result_6.csv true_label_file_name=GData_test_origin_6.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_6.txt
python train.py file_name=../1_year_data/GData_train_7.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_7.m pca=True pca_name=pca_7.m model_name=model_7.m
python test.py file_name=../1_year_data/GData_test_7.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_7.m pca_name=pca_7.m model_name=model_7.m record_name=result_7.csv
python analyse_result.py predict_label_file_name=svm_result_7.csv true_label_file_name=GData_test_origin_7.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_7.txt
python train.py file_name=../1_year_data/GData_train_8.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_8.m pca=True pca_name=pca_8.m model_name=model_8.m
python test.py file_name=../1_year_data/GData_test_8.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_8.m pca_name=pca_8.m model_name=model_8.m record_name=result_8.csv
python analyse_result.py predict_label_file_name=svm_result_8.csv true_label_file_name=GData_test_origin_8.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_8.txt
python train.py file_name=../1_year_data/GData_train_9.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_9.m pca=True pca_name=pca_9.m model_name=model_9.m
python test.py file_name=../1_year_data/GData_test_9.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_9.m pca_name=pca_9.m model_name=model_9.m record_name=result_9.csv
python analyse_result.py predict_label_file_name=svm_result_9.csv true_label_file_name=GData_test_origin_9.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_9.txt
python train.py file_name=../1_year_data/GData_train_10.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_10.m pca=True pca_name=pca_10.m model_name=model_10.m
python test.py file_name=../1_year_data/GData_test_10.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_10.m pca_name=pca_10.m model_name=model_10.m record_name=result_10.csv
python analyse_result.py predict_label_file_name=svm_result_10.csv true_label_file_name=GData_test_origin_10.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_10.txt
python train.py file_name=../1_year_data/GData_train_11.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_11.m pca=True pca_name=pca_11.m model_name=model_11.m
python test.py file_name=../1_year_data/GData_test_11.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_11.m pca_name=pca_11.m model_name=model_11.m record_name=result_11.csv
python analyse_result.py predict_label_file_name=svm_result_11.csv true_label_file_name=GData_test_origin_11.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_11.txt
python train.py file_name=../1_year_data/GData_train_12.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_12.m pca=True pca_name=pca_12.m model_name=model_12.m
python test.py file_name=../1_year_data/GData_test_12.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_12.m pca_name=pca_12.m model_name=model_12.m record_name=result_12.csv
python analyse_result.py predict_label_file_name=svm_result_12.csv true_label_file_name=GData_test_origin_12.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_12.txt
python train.py file_name=../1_year_data/GData_train_13.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_13.m pca=True pca_name=pca_13.m model_name=model_13.m
python test.py file_name=../1_year_data/GData_test_13.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_13.m pca_name=pca_13.m model_name=model_13.m record_name=result_13.csv
python analyse_result.py predict_label_file_name=svm_result_13.csv true_label_file_name=GData_test_origin_13.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_13.txt
python train.py file_name=../1_year_data/GData_train_14.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_14.m pca=True pca_name=pca_14.m model_name=model_14.m
python test.py file_name=../1_year_data/GData_test_14.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_14.m pca_name=pca_14.m model_name=model_14.m record_name=result_14.csv
python analyse_result.py predict_label_file_name=svm_result_14.csv true_label_file_name=GData_test_origin_14.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_14.txt
python train.py file_name=../1_year_data/GData_train_15.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_15.m pca=True pca_name=pca_15.m model_name=model_15.m
python test.py file_name=../1_year_data/GData_test_15.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_15.m pca_name=pca_15.m model_name=model_15.m record_name=result_15.csv
python analyse_result.py predict_label_file_name=svm_result_15.csv true_label_file_name=GData_test_origin_15.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_15.txt
python train.py file_name=../1_year_data/GData_train_16.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_16.m pca=True pca_name=pca_16.m model_name=model_16.m
python test.py file_name=../1_year_data/GData_test_16.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_16.m pca_name=pca_16.m model_name=model_16.m record_name=result_16.csv
python analyse_result.py predict_label_file_name=svm_result_16.csv true_label_file_name=GData_test_origin_16.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_16.txt
python train.py file_name=../1_year_data/GData_train_17.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_17.m pca=True pca_name=pca_17.m model_name=model_17.m
python test.py file_name=../1_year_data/GData_test_17.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_17.m pca_name=pca_17.m model_name=model_17.m record_name=result_17.csv
python analyse_result.py predict_label_file_name=svm_result_17.csv true_label_file_name=GData_test_origin_17.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_17.txt
python train.py file_name=../1_year_data/GData_train_18.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_18.m pca=True pca_name=pca_18.m model_name=model_18.m
python test.py file_name=../1_year_data/GData_test_18.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_18.m pca_name=pca_18.m model_name=model_18.m record_name=result_18.csv
python analyse_result.py predict_label_file_name=svm_result_18.csv true_label_file_name=GData_test_origin_18.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_18.txt
python train.py file_name=../1_year_data/GData_train_19.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_19.m pca=True pca_name=pca_19.m model_name=model_19.m
python test.py file_name=../1_year_data/GData_test_19.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_19.m pca_name=pca_19.m model_name=model_19.m record_name=result_19.csv
python analyse_result.py predict_label_file_name=svm_result_19.csv true_label_file_name=GData_test_origin_19.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_19.txt
python train.py file_name=../1_year_data/GData_train_20.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_20.m pca=True pca_name=pca_20.m model_name=model_20.m
python test.py file_name=../1_year_data/GData_test_20.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_20.m pca_name=pca_20.m model_name=model_20.m record_name=result_20.csv
python analyse_result.py predict_label_file_name=svm_result_20.csv true_label_file_name=GData_test_origin_20.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_20.txt
python train.py file_name=../1_year_data/GData_train_21.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_21.m pca=True pca_name=pca_21.m model_name=model_21.m
python test.py file_name=../1_year_data/GData_test_21.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_21.m pca_name=pca_21.m model_name=model_21.m record_name=result_21.csv
python analyse_result.py predict_label_file_name=svm_result_21.csv true_label_file_name=GData_test_origin_21.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_21.txt
python train.py file_name=../1_year_data/GData_train_22.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_22.m pca=True pca_name=pca_22.m model_name=model_22.m
python test.py file_name=../1_year_data/GData_test_22.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_22.m pca_name=pca_22.m model_name=model_22.m record_name=result_22.csv
python analyse_result.py predict_label_file_name=svm_result_22.csv true_label_file_name=GData_test_origin_22.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_22.txt
python train.py file_name=../1_year_data/GData_train_23.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_23.m pca=True pca_name=pca_23.m model_name=model_23.m
python test.py file_name=../1_year_data/GData_test_23.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_23.m pca_name=pca_23.m model_name=model_23.m record_name=result_23.csv
python analyse_result.py predict_label_file_name=svm_result_23.csv true_label_file_name=GData_test_origin_23.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_23.txt
python train.py file_name=../1_year_data/GData_train_24.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_24.m pca=True pca_name=pca_24.m model_name=model_24.m
python test.py file_name=../1_year_data/GData_test_24.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_24.m pca_name=pca_24.m model_name=model_24.m record_name=result_24.csv
python analyse_result.py predict_label_file_name=svm_result_24.csv true_label_file_name=GData_test_origin_24.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_24.txt
python train.py file_name=../1_year_data/GData_train_25.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_25.m pca=True pca_name=pca_25.m model_name=model_25.m
python test.py file_name=../1_year_data/GData_test_25.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_25.m pca_name=pca_25.m model_name=model_25.m record_name=result_25.csv
python analyse_result.py predict_label_file_name=svm_result_25.csv true_label_file_name=GData_test_origin_25.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_25.txt
python train.py file_name=../1_year_data/GData_train_26.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_26.m pca=True pca_name=pca_26.m model_name=model_26.m
python test.py file_name=../1_year_data/GData_test_26.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_26.m pca_name=pca_26.m model_name=model_26.m record_name=result_26.csv
python analyse_result.py predict_label_file_name=svm_result_26.csv true_label_file_name=GData_test_origin_26.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_26.txt
python train.py file_name=../1_year_data/GData_train_27.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_27.m pca=True pca_name=pca_27.m model_name=model_27.m
python test.py file_name=../1_year_data/GData_test_27.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_27.m pca_name=pca_27.m model_name=model_27.m record_name=result_27.csv
python analyse_result.py predict_label_file_name=svm_result_27.csv true_label_file_name=GData_test_origin_27.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_27.txt
python train.py file_name=../1_year_data/GData_train_28.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_28.m pca=True pca_name=pca_28.m model_name=model_28.m
python test.py file_name=../1_year_data/GData_test_28.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_28.m pca_name=pca_28.m model_name=model_28.m record_name=result_28.csv
python analyse_result.py predict_label_file_name=svm_result_28.csv true_label_file_name=GData_test_origin_28.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_28.txt
python train.py file_name=../1_year_data/GData_train_29.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_29.m pca=True pca_name=pca_29.m model_name=model_29.m
python test.py file_name=../1_year_data/GData_test_29.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_29.m pca_name=pca_29.m model_name=model_29.m record_name=result_29.csv
python analyse_result.py predict_label_file_name=svm_result_29.csv true_label_file_name=GData_test_origin_29.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_29.txt
python train.py file_name=../1_year_data/GData_train_30.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_30.m pca=True pca_name=pca_30.m model_name=model_30.m
python test.py file_name=../1_year_data/GData_test_30.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_30.m pca_name=pca_30.m model_name=model_30.m record_name=result_30.csv
python analyse_result.py predict_label_file_name=svm_result_30.csv true_label_file_name=GData_test_origin_30.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_30.txt
python train.py file_name=../1_year_data/GData_train_31.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_31.m pca=True pca_name=pca_31.m model_name=model_31.m
python test.py file_name=../1_year_data/GData_test_31.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_31.m pca_name=pca_31.m model_name=model_31.m record_name=result_31.csv
python analyse_result.py predict_label_file_name=svm_result_31.csv true_label_file_name=GData_test_origin_31.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_31.txt
python train.py file_name=../1_year_data/GData_train_32.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_32.m pca=True pca_name=pca_32.m model_name=model_32.m
python test.py file_name=../1_year_data/GData_test_32.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_32.m pca_name=pca_32.m model_name=model_32.m record_name=result_32.csv
python analyse_result.py predict_label_file_name=svm_result_32.csv true_label_file_name=GData_test_origin_32.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_32.txt
python train.py file_name=../1_year_data/GData_train_33.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_33.m pca=True pca_name=pca_33.m model_name=model_33.m
python test.py file_name=../1_year_data/GData_test_33.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_33.m pca_name=pca_33.m model_name=model_33.m record_name=result_33.csv
python analyse_result.py predict_label_file_name=svm_result_33.csv true_label_file_name=GData_test_origin_33.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_33.txt
python train.py file_name=../1_year_data/GData_train_34.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_34.m pca=True pca_name=pca_34.m model_name=model_34.m
python test.py file_name=../1_year_data/GData_test_34.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_34.m pca_name=pca_34.m model_name=model_34.m record_name=result_34.csv
python analyse_result.py predict_label_file_name=svm_result_34.csv true_label_file_name=GData_test_origin_34.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_34.txt
python train.py file_name=../1_year_data/GData_train_35.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_35.m pca=True pca_name=pca_35.m model_name=model_35.m
python test.py file_name=../1_year_data/GData_test_35.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_35.m pca_name=pca_35.m model_name=model_35.m record_name=result_35.csv
python analyse_result.py predict_label_file_name=svm_result_35.csv true_label_file_name=GData_test_origin_35.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_35.txt
python train.py file_name=../1_year_data/GData_train_36.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_36.m pca=True pca_name=pca_36.m model_name=model_36.m
python test.py file_name=../1_year_data/GData_test_36.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_36.m pca_name=pca_36.m model_name=model_36.m record_name=result_36.csv
python analyse_result.py predict_label_file_name=svm_result_36.csv true_label_file_name=GData_test_origin_36.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_36.txt
python train.py file_name=../1_year_data/GData_train_37.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_37.m pca=True pca_name=pca_37.m model_name=model_37.m
python test.py file_name=../1_year_data/GData_test_37.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_37.m pca_name=pca_37.m model_name=model_37.m record_name=result_37.csv
python analyse_result.py predict_label_file_name=svm_result_37.csv true_label_file_name=GData_test_origin_37.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_37.txt
python train.py file_name=../1_year_data/GData_train_38.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_38.m pca=True pca_name=pca_38.m model_name=model_38.m
python test.py file_name=../1_year_data/GData_test_38.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_38.m pca_name=pca_38.m model_name=model_38.m record_name=result_38.csv
python analyse_result.py predict_label_file_name=svm_result_38.csv true_label_file_name=GData_test_origin_38.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_38.txt
python train.py file_name=../1_year_data/GData_train_39.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_39.m pca=True pca_name=pca_39.m model_name=model_39.m
python test.py file_name=../1_year_data/GData_test_39.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_39.m pca_name=pca_39.m model_name=model_39.m record_name=result_39.csv
python analyse_result.py predict_label_file_name=svm_result_39.csv true_label_file_name=GData_test_origin_39.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_39.txt
python train.py file_name=../1_year_data/GData_train_40.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_40.m pca=True pca_name=pca_40.m model_name=model_40.m
python test.py file_name=../1_year_data/GData_test_40.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_40.m pca_name=pca_40.m model_name=model_40.m record_name=result_40.csv
python analyse_result.py predict_label_file_name=svm_result_40.csv true_label_file_name=GData_test_origin_40.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_40.txt
python train.py file_name=../1_year_data/GData_train_41.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_41.m pca=True pca_name=pca_41.m model_name=model_41.m
python test.py file_name=../1_year_data/GData_test_41.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_41.m pca_name=pca_41.m model_name=model_41.m record_name=result_41.csv
python analyse_result.py predict_label_file_name=svm_result_41.csv true_label_file_name=GData_test_origin_41.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_41.txt
python train.py file_name=../1_year_data/GData_train_42.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_42.m pca=True pca_name=pca_42.m model_name=model_42.m
python test.py file_name=../1_year_data/GData_test_42.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_42.m pca_name=pca_42.m model_name=model_42.m record_name=result_42.csv
python analyse_result.py predict_label_file_name=svm_result_42.csv true_label_file_name=GData_test_origin_42.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_42.txt
python train.py file_name=../1_year_data/GData_train_43.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_43.m pca=True pca_name=pca_43.m model_name=model_43.m
python test.py file_name=../1_year_data/GData_test_43.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_43.m pca_name=pca_43.m model_name=model_43.m record_name=result_43.csv
python analyse_result.py predict_label_file_name=svm_result_43.csv true_label_file_name=GData_test_origin_43.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_43.txt
python train.py file_name=../1_year_data/GData_train_44.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_44.m pca=True pca_name=pca_44.m model_name=model_44.m
python test.py file_name=../1_year_data/GData_test_44.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_44.m pca_name=pca_44.m model_name=model_44.m record_name=result_44.csv
python analyse_result.py predict_label_file_name=svm_result_44.csv true_label_file_name=GData_test_origin_44.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_44.txt
python train.py file_name=../1_year_data/GData_train_45.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_45.m pca=True pca_name=pca_45.m model_name=model_45.m
python test.py file_name=../1_year_data/GData_test_45.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_45.m pca_name=pca_45.m model_name=model_45.m record_name=result_45.csv
python analyse_result.py predict_label_file_name=svm_result_45.csv true_label_file_name=GData_test_origin_45.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_45.txt
python train.py file_name=../1_year_data/GData_train_46.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_46.m pca=True pca_name=pca_46.m model_name=model_46.m
python test.py file_name=../1_year_data/GData_test_46.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_46.m pca_name=pca_46.m model_name=model_46.m record_name=result_46.csv
python analyse_result.py predict_label_file_name=svm_result_46.csv true_label_file_name=GData_test_origin_46.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_46.txt
python train.py file_name=../1_year_data/GData_train_47.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_47.m pca=True pca_name=pca_47.m model_name=model_47.m
python test.py file_name=../1_year_data/GData_test_47.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_47.m pca_name=pca_47.m model_name=model_47.m record_name=result_47.csv
python analyse_result.py predict_label_file_name=svm_result_47.csv true_label_file_name=GData_test_origin_47.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_47.txt
python train.py file_name=../1_year_data/GData_train_48.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_48.m pca=True pca_name=pca_48.m model_name=model_48.m
python test.py file_name=../1_year_data/GData_test_48.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_48.m pca_name=pca_48.m model_name=model_48.m record_name=result_48.csv
python analyse_result.py predict_label_file_name=svm_result_48.csv true_label_file_name=GData_test_origin_48.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_48.txt
python train.py file_name=../1_year_data/GData_train_49.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_49.m pca=True pca_name=pca_49.m model_name=model_49.m
python test.py file_name=../1_year_data/GData_test_49.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_49.m pca_name=pca_49.m model_name=model_49.m record_name=result_49.csv
python analyse_result.py predict_label_file_name=svm_result_49.csv true_label_file_name=GData_test_origin_49.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_49.txt
python train.py file_name=../1_year_data/GData_train_50.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_50.m pca=True pca_name=pca_50.m model_name=model_50.m
python test.py file_name=../1_year_data/GData_test_50.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_50.m pca_name=pca_50.m model_name=model_50.m record_name=result_50.csv
python analyse_result.py predict_label_file_name=svm_result_50.csv true_label_file_name=GData_test_origin_50.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_50.txt
python train.py file_name=../1_year_data/GData_train_51.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_51.m pca=True pca_name=pca_51.m model_name=model_51.m
python test.py file_name=../1_year_data/GData_test_51.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_51.m pca_name=pca_51.m model_name=model_51.m record_name=result_51.csv
python analyse_result.py predict_label_file_name=svm_result_51.csv true_label_file_name=GData_test_origin_51.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_51.txt
python train.py file_name=../1_year_data/GData_train_52.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_52.m pca=True pca_name=pca_52.m model_name=model_52.m
python test.py file_name=../1_year_data/GData_test_52.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_52.m pca_name=pca_52.m model_name=model_52.m record_name=result_52.csv
python analyse_result.py predict_label_file_name=svm_result_52.csv true_label_file_name=GData_test_origin_52.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_52.txt
python train.py file_name=../1_year_data/GData_train_53.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_53.m pca=True pca_name=pca_53.m model_name=model_53.m
python test.py file_name=../1_year_data/GData_test_53.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_53.m pca_name=pca_53.m model_name=model_53.m record_name=result_53.csv
python analyse_result.py predict_label_file_name=svm_result_53.csv true_label_file_name=GData_test_origin_53.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_53.txt
python train.py file_name=../1_year_data/GData_train_54.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_54.m pca=True pca_name=pca_54.m model_name=model_54.m
python test.py file_name=../1_year_data/GData_test_54.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_54.m pca_name=pca_54.m model_name=model_54.m record_name=result_54.csv
python analyse_result.py predict_label_file_name=svm_result_54.csv true_label_file_name=GData_test_origin_54.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_54.txt
python train.py file_name=../1_year_data/GData_train_55.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_55.m pca=True pca_name=pca_55.m model_name=model_55.m
python test.py file_name=../1_year_data/GData_test_55.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_55.m pca_name=pca_55.m model_name=model_55.m record_name=result_55.csv
python analyse_result.py predict_label_file_name=svm_result_55.csv true_label_file_name=GData_test_origin_55.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_55.txt
python train.py file_name=../1_year_data/GData_train_56.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_56.m pca=True pca_name=pca_56.m model_name=model_56.m
python test.py file_name=../1_year_data/GData_test_56.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_56.m pca_name=pca_56.m model_name=model_56.m record_name=result_56.csv
python analyse_result.py predict_label_file_name=svm_result_56.csv true_label_file_name=GData_test_origin_56.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_56.txt
python train.py file_name=../1_year_data/GData_train_57.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_57.m pca=True pca_name=pca_57.m model_name=model_57.m
python test.py file_name=../1_year_data/GData_test_57.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_57.m pca_name=pca_57.m model_name=model_57.m record_name=result_57.csv
python analyse_result.py predict_label_file_name=svm_result_57.csv true_label_file_name=GData_test_origin_57.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_57.txt
python train.py file_name=../1_year_data/GData_train_58.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_58.m pca=True pca_name=pca_58.m model_name=model_58.m
python test.py file_name=../1_year_data/GData_test_58.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_58.m pca_name=pca_58.m model_name=model_58.m record_name=result_58.csv
python analyse_result.py predict_label_file_name=svm_result_58.csv true_label_file_name=GData_test_origin_58.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_58.txt
python train.py file_name=../1_year_data/GData_train_59.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_59.m pca=True pca_name=pca_59.m model_name=model_59.m
python test.py file_name=../1_year_data/GData_test_59.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_59.m pca_name=pca_59.m model_name=model_59.m record_name=result_59.csv
python analyse_result.py predict_label_file_name=svm_result_59.csv true_label_file_name=GData_test_origin_59.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_59.txt
python train.py file_name=../1_year_data/GData_train_60.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_60.m pca=True pca_name=pca_60.m model_name=model_60.m
python test.py file_name=../1_year_data/GData_test_60.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_60.m pca_name=pca_60.m model_name=model_60.m record_name=result_60.csv
python analyse_result.py predict_label_file_name=svm_result_60.csv true_label_file_name=GData_test_origin_60.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_60.txt
python train.py file_name=../1_year_data/GData_train_61.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_61.m pca=True pca_name=pca_61.m model_name=model_61.m
python test.py file_name=../1_year_data/GData_test_61.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_61.m pca_name=pca_61.m model_name=model_61.m record_name=result_61.csv
python analyse_result.py predict_label_file_name=svm_result_61.csv true_label_file_name=GData_test_origin_61.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_61.txt
python train.py file_name=../1_year_data/GData_train_62.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_62.m pca=True pca_name=pca_62.m model_name=model_62.m
python test.py file_name=../1_year_data/GData_test_62.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_62.m pca_name=pca_62.m model_name=model_62.m record_name=result_62.csv
python analyse_result.py predict_label_file_name=svm_result_62.csv true_label_file_name=GData_test_origin_62.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_62.txt
python train.py file_name=../1_year_data/GData_train_63.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_63.m pca=True pca_name=pca_63.m model_name=model_63.m
python test.py file_name=../1_year_data/GData_test_63.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_63.m pca_name=pca_63.m model_name=model_63.m record_name=result_63.csv
python analyse_result.py predict_label_file_name=svm_result_63.csv true_label_file_name=GData_test_origin_63.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_63.txt
python train.py file_name=../1_year_data/GData_train_64.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_64.m pca=True pca_name=pca_64.m model_name=model_64.m
python test.py file_name=../1_year_data/GData_test_64.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_64.m pca_name=pca_64.m model_name=model_64.m record_name=result_64.csv
python analyse_result.py predict_label_file_name=svm_result_64.csv true_label_file_name=GData_test_origin_64.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_64.txt
python train.py file_name=../1_year_data/GData_train_65.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_65.m pca=True pca_name=pca_65.m model_name=model_65.m
python test.py file_name=../1_year_data/GData_test_65.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_65.m pca_name=pca_65.m model_name=model_65.m record_name=result_65.csv
python analyse_result.py predict_label_file_name=svm_result_65.csv true_label_file_name=GData_test_origin_65.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_65.txt
python train.py file_name=../1_year_data/GData_train_66.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_66.m pca=True pca_name=pca_66.m model_name=model_66.m
python test.py file_name=../1_year_data/GData_test_66.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_66.m pca_name=pca_66.m model_name=model_66.m record_name=result_66.csv
python analyse_result.py predict_label_file_name=svm_result_66.csv true_label_file_name=GData_test_origin_66.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_66.txt
python train.py file_name=../1_year_data/GData_train_67.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_67.m pca=True pca_name=pca_67.m model_name=model_67.m
python test.py file_name=../1_year_data/GData_test_67.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_67.m pca_name=pca_67.m model_name=model_67.m record_name=result_67.csv
python analyse_result.py predict_label_file_name=svm_result_67.csv true_label_file_name=GData_test_origin_67.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_67.txt
python train.py file_name=../1_year_data/GData_train_68.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_68.m pca=True pca_name=pca_68.m model_name=model_68.m
python test.py file_name=../1_year_data/GData_test_68.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_68.m pca_name=pca_68.m model_name=model_68.m record_name=result_68.csv
python analyse_result.py predict_label_file_name=svm_result_68.csv true_label_file_name=GData_test_origin_68.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_68.txt
python train.py file_name=../1_year_data/GData_train_69.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_69.m pca=True pca_name=pca_69.m model_name=model_69.m
python test.py file_name=../1_year_data/GData_test_69.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_69.m pca_name=pca_69.m model_name=model_69.m record_name=result_69.csv
python analyse_result.py predict_label_file_name=svm_result_69.csv true_label_file_name=GData_test_origin_69.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_69.txt
python train.py file_name=../1_year_data/GData_train_70.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_70.m pca=True pca_name=pca_70.m model_name=model_70.m
python test.py file_name=../1_year_data/GData_test_70.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_70.m pca_name=pca_70.m model_name=model_70.m record_name=result_70.csv
python analyse_result.py predict_label_file_name=svm_result_70.csv true_label_file_name=GData_test_origin_70.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_70.txt
python train.py file_name=../1_year_data/GData_train_71.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_71.m pca=True pca_name=pca_71.m model_name=model_71.m
python test.py file_name=../1_year_data/GData_test_71.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_71.m pca_name=pca_71.m model_name=model_71.m record_name=result_71.csv
python analyse_result.py predict_label_file_name=svm_result_71.csv true_label_file_name=GData_test_origin_71.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_71.txt
python train.py file_name=../1_year_data/GData_train_72.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_72.m pca=True pca_name=pca_72.m model_name=model_72.m
python test.py file_name=../1_year_data/GData_test_72.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_72.m pca_name=pca_72.m model_name=model_72.m record_name=result_72.csv
python analyse_result.py predict_label_file_name=svm_result_72.csv true_label_file_name=GData_test_origin_72.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_72.txt
python train.py file_name=../1_year_data/GData_train_73.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_73.m pca=True pca_name=pca_73.m model_name=model_73.m
python test.py file_name=../1_year_data/GData_test_73.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_73.m pca_name=pca_73.m model_name=model_73.m record_name=result_73.csv
python analyse_result.py predict_label_file_name=svm_result_73.csv true_label_file_name=GData_test_origin_73.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_73.txt
python train.py file_name=../1_year_data/GData_train_74.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_74.m pca=True pca_name=pca_74.m model_name=model_74.m
python test.py file_name=../1_year_data/GData_test_74.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_74.m pca_name=pca_74.m model_name=model_74.m record_name=result_74.csv
python analyse_result.py predict_label_file_name=svm_result_74.csv true_label_file_name=GData_test_origin_74.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_74.txt
python train.py file_name=../1_year_data/GData_train_75.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_75.m pca=True pca_name=pca_75.m model_name=model_75.m
python test.py file_name=../1_year_data/GData_test_75.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_75.m pca_name=pca_75.m model_name=model_75.m record_name=result_75.csv
python analyse_result.py predict_label_file_name=svm_result_75.csv true_label_file_name=GData_test_origin_75.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_75.txt
python train.py file_name=../1_year_data/GData_train_76.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_76.m pca=True pca_name=pca_76.m model_name=model_76.m
python test.py file_name=../1_year_data/GData_test_76.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_76.m pca_name=pca_76.m model_name=model_76.m record_name=result_76.csv
python analyse_result.py predict_label_file_name=svm_result_76.csv true_label_file_name=GData_test_origin_76.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_76.txt
python train.py file_name=../1_year_data/GData_train_77.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_77.m pca=True pca_name=pca_77.m model_name=model_77.m
python test.py file_name=../1_year_data/GData_test_77.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_77.m pca_name=pca_77.m model_name=model_77.m record_name=result_77.csv
python analyse_result.py predict_label_file_name=svm_result_77.csv true_label_file_name=GData_test_origin_77.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_77.txt
python train.py file_name=../1_year_data/GData_train_78.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_78.m pca=True pca_name=pca_78.m model_name=model_78.m
python test.py file_name=../1_year_data/GData_test_78.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_78.m pca_name=pca_78.m model_name=model_78.m record_name=result_78.csv
python analyse_result.py predict_label_file_name=svm_result_78.csv true_label_file_name=GData_test_origin_78.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_78.txt
python train.py file_name=../1_year_data/GData_train_79.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_79.m pca=True pca_name=pca_79.m model_name=model_79.m
python test.py file_name=../1_year_data/GData_test_79.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_79.m pca_name=pca_79.m model_name=model_79.m record_name=result_79.csv
python analyse_result.py predict_label_file_name=svm_result_79.csv true_label_file_name=GData_test_origin_79.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_79.txt
python train.py file_name=../1_year_data/GData_train_80.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_80.m pca=True pca_name=pca_80.m model_name=model_80.m
python test.py file_name=../1_year_data/GData_test_80.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_80.m pca_name=pca_80.m model_name=model_80.m record_name=result_80.csv
python analyse_result.py predict_label_file_name=svm_result_80.csv true_label_file_name=GData_test_origin_80.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_80.txt
python train.py file_name=../1_year_data/GData_train_81.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_81.m pca=True pca_name=pca_81.m model_name=model_81.m
python test.py file_name=../1_year_data/GData_test_81.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_81.m pca_name=pca_81.m model_name=model_81.m record_name=result_81.csv
python analyse_result.py predict_label_file_name=svm_result_81.csv true_label_file_name=GData_test_origin_81.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_81.txt
python train.py file_name=../1_year_data/GData_train_82.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_82.m pca=True pca_name=pca_82.m model_name=model_82.m
python test.py file_name=../1_year_data/GData_test_82.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_82.m pca_name=pca_82.m model_name=model_82.m record_name=result_82.csv
python analyse_result.py predict_label_file_name=svm_result_82.csv true_label_file_name=GData_test_origin_82.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_82.txt
python train.py file_name=../1_year_data/GData_train_83.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_83.m pca=True pca_name=pca_83.m model_name=model_83.m
python test.py file_name=../1_year_data/GData_test_83.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_83.m pca_name=pca_83.m model_name=model_83.m record_name=result_83.csv
python analyse_result.py predict_label_file_name=svm_result_83.csv true_label_file_name=GData_test_origin_83.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_83.txt
python train.py file_name=../1_year_data/GData_train_84.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_84.m pca=True pca_name=pca_84.m model_name=model_84.m
python test.py file_name=../1_year_data/GData_test_84.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_84.m pca_name=pca_84.m model_name=model_84.m record_name=result_84.csv
python analyse_result.py predict_label_file_name=svm_result_84.csv true_label_file_name=GData_test_origin_84.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_84.txt
python train.py file_name=../1_year_data/GData_train_85.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_85.m pca=True pca_name=pca_85.m model_name=model_85.m
python test.py file_name=../1_year_data/GData_test_85.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_85.m pca_name=pca_85.m model_name=model_85.m record_name=result_85.csv
python analyse_result.py predict_label_file_name=svm_result_85.csv true_label_file_name=GData_test_origin_85.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_85.txt
python train.py file_name=../1_year_data/GData_train_86.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_86.m pca=True pca_name=pca_86.m model_name=model_86.m
python test.py file_name=../1_year_data/GData_test_86.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_86.m pca_name=pca_86.m model_name=model_86.m record_name=result_86.csv
python analyse_result.py predict_label_file_name=svm_result_86.csv true_label_file_name=GData_test_origin_86.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_86.txt
python train.py file_name=../1_year_data/GData_train_87.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_87.m pca=True pca_name=pca_87.m model_name=model_87.m
python test.py file_name=../1_year_data/GData_test_87.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm scaler_name=scaler_87.m pca_name=pca_87.m model_name=model_87.m record_name=result_87.csv
python analyse_result.py predict_label_file_name=svm_result_87.csv true_label_file_name=GData_test_origin_87.csv model_record_path=../1_year_result/model_4/ file_record_path=../1_year_result/record_4/ method_name=svm winner_number=3 record_name=result_87.txt
